import { GithubIcon } from '../components/icons'

import {
  Html5Icon,
  Css3Icon,
  JSIcon,
  TypeScriptIcon,
  ReactIcon,
  NextJSIcon,
  TailwindCSSIcon,
  NodeJSIcon,
  GoIcon,
  GraphQLIcon,
  MongoDbIcon,
  AWSIcon,
  TurborepoIcon,
  VercelIcon,
  VitestIcon,
  CypressIcon,
  ContentfulIcon,
  StoryblokIcon,
  WordpressIcon,
  StorybookIcon,
  RudderStackIcon,
  MixpanelIcon,
  VoucherifyIcon,
  ExpressJsIcon,
  GoogleCloudIcon,
  HandlebarsIcon,
  MaterialUIIcon,
  BootstrapIcon,
  NextUILogo,
  JestIcon,
} from '@/components/techIcons'

export const technology = {
  HTML: { name: 'HTML', icon: Html5Icon },
  CSS: { name: 'CSS', icon: Css3Icon },
  JavaScript: { name: 'JavaScript', icon: JSIcon },
  TypeScript: { name: 'TypeScript', icon: TypeScriptIcon },
  ReactJS: { name: 'ReactJS', icon: ReactIcon },
  NextJS: { name: 'NextJS', icon: NextJSIcon },
  TailwindCSS: { name: 'TailwindCSS', icon: TailwindCSSIcon },
  NodeJS: { name: 'NodeJS', icon: NodeJSIcon },
  GO: { name: 'GO', icon: GoIcon },
  GraphQL: { name: 'GraphQL', icon: GraphQLIcon },
  MongoDB: { name: 'MongoDB', icon: MongoDbIcon },
  AWS: { name: 'AWS', icon: AWSIcon },
  Turborepo: { name: 'Turborepo', icon: TurborepoIcon },
  Vercel: { name: 'Vercel', icon: VercelIcon },
  Jest: { name: 'Jest', icon: JestIcon },
  Vitest: { name: 'Vitest', icon: VitestIcon },
  Cypress: { name: 'Cypress', icon: CypressIcon },
  Contentful: { name: 'Contentful', icon: ContentfulIcon },
  Storyblok: { name: 'Storyblok', icon: StoryblokIcon },
  Wordpress: { name: 'Wordpress', icon: WordpressIcon },
  Storybook: { name: 'Storybook', icon: StorybookIcon },
  RudderStack: { name: 'RudderStack', icon: RudderStackIcon },
  Mixpanel: { name: 'Mixpanel', icon: MixpanelIcon },
  Voucherify: { name: 'Voucherify', icon: VoucherifyIcon },
  MaterialUI: { name: 'Material UI', icon: MaterialUIIcon },
  NextUI: { name: 'NextUI', icon: NextUILogo },
  Bootstrap: { name: 'Bootstrap', icon: BootstrapIcon },
  ExpressJS: { name: 'Express.js', icon: ExpressJsIcon },
  GoogleCloud: { name: 'Google Cloud', icon: GoogleCloudIcon },
  Handlebars: { name: 'Handlebars', icon: HandlebarsIcon },
  GitHub: { name: 'GitHub', icon: GithubIcon },
}
